### ISSUE TITLE
Implementing Bottom Navbar, Card, Creating Home Page and About Page, Star 

### ISSUE THREAD

**Issue by KirantiLoh** [calon-ristek/cari-makan#1]
## Overview
Kita perlu bikin MVP dari web nya

## Tasks

- [x] Bikin komponen bottom nav
- [x] Bikin Home Page 
- [x] Bikin komponen Card untuk kantin
- [x] Bikin komponen Star
- [x] Bikin About Page
